# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  carbon-now-nvim = {
    pname = "carbon-now-nvim";
    version = "e64e29e5b89d20548e792b3d6c3995c08d7ee636";
    src = fetchFromGitHub ({
      owner = "ellisonleao";
      repo = "carbon-now.nvim";
      rev = "e64e29e5b89d20548e792b3d6c3995c08d7ee636";
      fetchSubmodules = false;
      sha256 = "sha256-v+Q9qCPrp7s14jeHJJq3pOUrx336+lo9zuwI/VYry5g=";
    });
    date = "2022-07-15";
  };
  cmp-fuzzy-path = {
    pname = "cmp-fuzzy-path";
    version = "18ee8f81ab704f3f6656cfe52180dec6f7b497a7";
    src = fetchFromGitHub ({
      owner = "tzachar";
      repo = "cmp-fuzzy-path";
      rev = "18ee8f81ab704f3f6656cfe52180dec6f7b497a7";
      fetchSubmodules = false;
      sha256 = "sha256-E77kTQf7OOciTwZFjR18uLraJ8EFkVjcc350Lffc0Zc=";
    });
    date = "2022-10-30";
  };
  discord-linux = {
    pname = "discord-linux";
    version = "0.0.21";
    src = fetchurl {
      url = "https://dl.discordapp.net/apps/linux/0.0.21/discord-0.0.21.tar.gz";
      sha256 = "sha256-KDKUssPRrs/D10s5GhJ23hctatQmyqd27xS9nU7iNaM=";
    };
  };
  discord-ptb-linux = {
    pname = "discord-ptb-linux";
    version = "0.0.34";
    src = fetchurl {
      url = "https://dl-ptb.discordapp.net/apps/linux/0.0.34/discord-ptb-0.0.34.tar.gz";
      sha256 = "sha256-CD6dLoBnlvhpwEFfLI9OqjhviZPj3xNDyPK9qBJUqck=";
    };
  };
  fuzzy-nvim = {
    pname = "fuzzy-nvim";
    version = "d5fee69b54ef400f0ccedf37917c4782e8929424";
    src = fetchFromGitHub ({
      owner = "tzachar";
      repo = "fuzzy.nvim";
      rev = "d5fee69b54ef400f0ccedf37917c4782e8929424";
      fetchSubmodules = false;
      sha256 = "sha256-znlS/F3lc6Ue0g0UPSWyifJBiWPvlLnJHtJpmVfl1fY=";
    });
    date = "2022-02-20";
  };
  git-blame-nvim = {
    pname = "git-blame-nvim";
    version = "d3afb1c57918720548effb42edec530232436378";
    src = fetchFromGitHub ({
      owner = "f-person";
      repo = "git-blame.nvim";
      rev = "d3afb1c57918720548effb42edec530232436378";
      fetchSubmodules = false;
      sha256 = "sha256-6imANfRFuY23A276CD8DWqHB89cyKN2TCKIQGG6elrc=";
    });
    date = "2022-11-06";
  };
  key-menu-nvim = {
    pname = "key-menu-nvim";
    version = "f63055d25c50ff961e6969e6a024fae4d64f92ee";
    src = fetchFromGitHub ({
      owner = "linty-org";
      repo = "key-menu.nvim";
      rev = "f63055d25c50ff961e6969e6a024fae4d64f92ee";
      fetchSubmodules = false;
      sha256 = "sha256-NPZuay1qF0FJ5nqckbCL0FWvYS0v72430TSwxIt6OzU=";
    });
    date = "2022-10-09";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  pest-vim = {
    pname = "pest-vim";
    version = "ebeeea5e0757adee037135cf3b8248589b22ae16";
    src = fetchFromGitHub ({
      owner = "pest-parser";
      repo = "pest.vim";
      rev = "ebeeea5e0757adee037135cf3b8248589b22ae16";
      fetchSubmodules = false;
      sha256 = "sha256-cbGq0CVkQGD89HoPmtZyYIrM0OIMSAZi4EeEbpJLMJU=";
    });
    date = "2020-04-20";
  };
  rust-vim = {
    pname = "rust-vim";
    version = "1cdc5cb4bd061bc30b502e07321682b5a4396dca";
    src = fetchgit {
      url = "https://github.com/rust-lang/rust.vim";
      rev = "1cdc5cb4bd061bc30b502e07321682b5a4396dca";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-70kp644jOtJ4wguty/SUFX+YEsoxW12LGg3vZh7BdPY=";
    };
    date = "2022-09-28";
  };
  telescope-file-browser-nvim = {
    pname = "telescope-file-browser-nvim";
    version = "2429ecfd2d76e3eb6c9f8d8ba2c6ce328975a95a";
    src = fetchFromGitHub ({
      owner = "nvim-telescope";
      repo = "telescope-file-browser.nvim";
      rev = "2429ecfd2d76e3eb6c9f8d8ba2c6ce328975a95a";
      fetchSubmodules = false;
      sha256 = "sha256-fIm2FWYJXNl0SlQgmRuULOTRc2VVv2p1jJ2slcP4veY=";
    });
    date = "2022-10-16";
  };
  tree-sitter-rust = {
    pname = "tree-sitter-rust";
    version = "67d304c81e3b2a6cda7e9f577c1f527c53c8348e";
    src = fetchFromGitHub ({
      owner = "tree-sitter";
      repo = "tree-sitter-rust";
      rev = "67d304c81e3b2a6cda7e9f577c1f527c53c8348e";
      fetchSubmodules = false;
      sha256 = "sha256-xxiqcCXWb3T12W4z+bnYmCWo4U6lyOFCBy2H2p7AHWI=";
    });
  };
  vim-dogrun = {
    pname = "vim-dogrun";
    version = "7622fa0d300dce9a9223797413b8d4f97417b7b5";
    src = fetchFromGitHub ({
      owner = "wadackel";
      repo = "vim-dogrun";
      rev = "7622fa0d300dce9a9223797413b8d4f97417b7b5";
      fetchSubmodules = false;
      sha256 = "sha256-K7ioTbi9oXm4gD4bv7QRyqU9t1tGBcjgtwHMeBPfRbw=";
    });
    date = "2022-11-06";
  };
}
