# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  carbon-now-nvim = {
    pname = "carbon-now-nvim";
    version = "e64e29e5b89d20548e792b3d6c3995c08d7ee636";
    src = fetchFromGitHub ({
      owner = "ellisonleao";
      repo = "carbon-now.nvim";
      rev = "e64e29e5b89d20548e792b3d6c3995c08d7ee636";
      fetchSubmodules = false;
      sha256 = "sha256-v+Q9qCPrp7s14jeHJJq3pOUrx336+lo9zuwI/VYry5g=";
    });
  };
  cmp-fuzzy-path = {
    pname = "cmp-fuzzy-path";
    version = "b4a8c1bebfe5a5d45b36e0b09e72f9f082e9a40c";
    src = fetchFromGitHub ({
      owner = "tzachar";
      repo = "cmp-fuzzy-path";
      rev = "b4a8c1bebfe5a5d45b36e0b09e72f9f082e9a40c";
      fetchSubmodules = false;
      sha256 = "sha256-Tszr7F51SC7rsbKHxg3GUjZYCCh5G9ru3VXgRWAF3X0=";
    });
  };
  discord-linux = {
    pname = "discord-linux";
    version = "0.0.18";
    src = fetchurl {
      url = "https://dl.discordapp.net/apps/linux/0.0.18/discord-0.0.18.tar.gz";
      sha256 = "sha256-BBc4n6Q3xuBE13JS3gz/6EcwdOWW57NLp2saOlwOgMI=";
    };
  };
  discord-ptb-linux = {
    pname = "discord-ptb-linux";
    version = "0.0.31";
    src = fetchurl {
      url = "https://dl-ptb.discordapp.net/apps/linux/0.0.31/discord-ptb-0.0.31.tar.gz";
      sha256 = "sha256-XQDfXMJekfk1lvWDniupfYCRBMYVeLJtF+iFS9qZ2xM=";
    };
  };
  fuzzy-nvim = {
    pname = "fuzzy-nvim";
    version = "d5fee69b54ef400f0ccedf37917c4782e8929424";
    src = fetchFromGitHub ({
      owner = "tzachar";
      repo = "fuzzy.nvim";
      rev = "d5fee69b54ef400f0ccedf37917c4782e8929424";
      fetchSubmodules = false;
      sha256 = "sha256-znlS/F3lc6Ue0g0UPSWyifJBiWPvlLnJHtJpmVfl1fY=";
    });
  };
  git-blame-nvim = {
    pname = "git-blame-nvim";
    version = "1bb73289929107309d2d90f7582ece5e9436bfd8";
    src = fetchFromGitHub ({
      owner = "f-person";
      repo = "git-blame.nvim";
      rev = "1bb73289929107309d2d90f7582ece5e9436bfd8";
      fetchSubmodules = false;
      sha256 = "sha256-GQGECWtVZFKNP6LcK6dxUK4gZpLgMxbZqqieest2yws=";
    });
  };
  key-menu-nvim = {
    pname = "key-menu-nvim";
    version = "6fcb95126c882d285f32d6f34f0e61d82fd516c1";
    src = fetchFromGitHub ({
      owner = "linty-org";
      repo = "key-menu.nvim";
      rev = "6fcb95126c882d285f32d6f34f0e61d82fd516c1";
      fetchSubmodules = false;
      sha256 = "sha256-3hIBHCthiOQJi9icVCNvIBiopvgw4iHtSCh/MZTJ1C4=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  pest-vim = {
    pname = "pest-vim";
    version = "ebeeea5e0757adee037135cf3b8248589b22ae16";
    src = fetchFromGitHub ({
      owner = "pest-parser";
      repo = "pest.vim";
      rev = "ebeeea5e0757adee037135cf3b8248589b22ae16";
      fetchSubmodules = false;
      sha256 = "sha256-cbGq0CVkQGD89HoPmtZyYIrM0OIMSAZi4EeEbpJLMJU=";
    });
  };
  polymc = {
    pname = "polymc";
    version = "1.4.0";
    src = fetchFromGitHub ({
      owner = "PolyMC";
      repo = "PolyMC";
      rev = "1.4.0";
      fetchSubmodules = true;
      sha256 = "sha256-gaPqCAC/tE6nUONgWSrVm3oBzSnOhZ5xiAJ+QyX+8rA=";
    });
  };
  telescope-file-browser-nvim = {
    pname = "telescope-file-browser-nvim";
    version = "c30fcb6214acf8538616e403e0f82a6430bf6801";
    src = fetchFromGitHub ({
      owner = "nvim-telescope";
      repo = "telescope-file-browser.nvim";
      rev = "c30fcb6214acf8538616e403e0f82a6430bf6801";
      fetchSubmodules = false;
      sha256 = "sha256-78mT73qlEcMTHmu9PRr7Vr0P4a2Ueu0W0sbgZPCm8Z4=";
    });
  };
  tree-sitter-rust = {
    pname = "tree-sitter-rust";
    version = "67d304c81e3b2a6cda7e9f577c1f527c53c8348e";
    src = fetchFromGitHub ({
      owner = "tree-sitter";
      repo = "tree-sitter-rust";
      rev = "67d304c81e3b2a6cda7e9f577c1f527c53c8348e";
      fetchSubmodules = false;
      sha256 = "sha256-xxiqcCXWb3T12W4z+bnYmCWo4U6lyOFCBy2H2p7AHWI=";
    });
  };
  vim-dogrun = {
    pname = "vim-dogrun";
    version = "f1a6ec680da5f2da7d8629dfa55fe222ae878c2d";
    src = fetchFromGitHub ({
      owner = "wadackel";
      repo = "vim-dogrun";
      rev = "f1a6ec680da5f2da7d8629dfa55fe222ae878c2d";
      fetchSubmodules = false;
      sha256 = "sha256-t2McCjljcROG+sGMJ5y4585si9I0man7XmQrWS2J9Xg=";
    });
  };
}
