# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  carbon-now-nvim = {
    pname = "carbon-now-nvim";
    version = "e64e29e5b89d20548e792b3d6c3995c08d7ee636";
    src = fetchFromGitHub ({
      owner = "ellisonleao";
      repo = "carbon-now.nvim";
      rev = "e64e29e5b89d20548e792b3d6c3995c08d7ee636";
      fetchSubmodules = false;
      sha256 = "sha256-v+Q9qCPrp7s14jeHJJq3pOUrx336+lo9zuwI/VYry5g=";
    });
    date = "2022-07-15";
  };
  cargo-lints = {
    pname = "cargo-lints";
    version = "2f8cad228c0add12352097a9ede0c54833ec18fb";
    src = fetchgit {
      url = "https://github.com/soramitsu/iroha2-cargo_lints";
      rev = "2f8cad228c0add12352097a9ede0c54833ec18fb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-L8+cpB7e1JdpAIfkWXRmX5u5ah1/gqA3rSW//OeO8SQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cargo-lints-2f8cad228c0add12352097a9ede0c54833ec18fb/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2022-06-07";
  };
  cmp-fuzzy-path = {
    pname = "cmp-fuzzy-path";
    version = "18ee8f81ab704f3f6656cfe52180dec6f7b497a7";
    src = fetchFromGitHub ({
      owner = "tzachar";
      repo = "cmp-fuzzy-path";
      rev = "18ee8f81ab704f3f6656cfe52180dec6f7b497a7";
      fetchSubmodules = false;
      sha256 = "sha256-E77kTQf7OOciTwZFjR18uLraJ8EFkVjcc350Lffc0Zc=";
    });
    date = "2022-10-30";
  };
  discord-linux = {
    pname = "discord-linux";
    version = "0.0.21";
    src = fetchurl {
      url = "https://dl.discordapp.net/apps/linux/0.0.21/discord-0.0.21.tar.gz";
      sha256 = "sha256-KDKUssPRrs/D10s5GhJ23hctatQmyqd27xS9nU7iNaM=";
    };
  };
  discord-ptb-linux = {
    pname = "discord-ptb-linux";
    version = "0.0.34";
    src = fetchurl {
      url = "https://dl-ptb.discordapp.net/apps/linux/0.0.34/discord-ptb-0.0.34.tar.gz";
      sha256 = "sha256-CD6dLoBnlvhpwEFfLI9OqjhviZPj3xNDyPK9qBJUqck=";
    };
  };
  fuzzy-nvim = {
    pname = "fuzzy-nvim";
    version = "04b3d969002b5fd2db23a33aaf33a13a533cbdbd";
    src = fetchFromGitHub ({
      owner = "tzachar";
      repo = "fuzzy.nvim";
      rev = "04b3d969002b5fd2db23a33aaf33a13a533cbdbd";
      fetchSubmodules = false;
      sha256 = "sha256-s0Z48Ve5aj1XsdrAuv53+T1T/jo1zThgaaTeAKtfg5U=";
    });
    date = "2022-11-15";
  };
  git-blame-nvim = {
    pname = "git-blame-nvim";
    version = "d3afb1c57918720548effb42edec530232436378";
    src = fetchFromGitHub ({
      owner = "f-person";
      repo = "git-blame.nvim";
      rev = "d3afb1c57918720548effb42edec530232436378";
      fetchSubmodules = false;
      sha256 = "sha256-6imANfRFuY23A276CD8DWqHB89cyKN2TCKIQGG6elrc=";
    });
    date = "2022-11-06";
  };
  key-menu-nvim = {
    pname = "key-menu-nvim";
    version = "f63055d25c50ff961e6969e6a024fae4d64f92ee";
    src = fetchFromGitHub ({
      owner = "linty-org";
      repo = "key-menu.nvim";
      rev = "f63055d25c50ff961e6969e6a024fae4d64f92ee";
      fetchSubmodules = false;
      sha256 = "sha256-NPZuay1qF0FJ5nqckbCL0FWvYS0v72430TSwxIt6OzU=";
    });
    date = "2022-10-09";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  pest-vim = {
    pname = "pest-vim";
    version = "ebeeea5e0757adee037135cf3b8248589b22ae16";
    src = fetchFromGitHub ({
      owner = "pest-parser";
      repo = "pest.vim";
      rev = "ebeeea5e0757adee037135cf3b8248589b22ae16";
      fetchSubmodules = false;
      sha256 = "sha256-cbGq0CVkQGD89HoPmtZyYIrM0OIMSAZi4EeEbpJLMJU=";
    });
    date = "2020-04-20";
  };
  rust-vim = {
    pname = "rust-vim";
    version = "1cdc5cb4bd061bc30b502e07321682b5a4396dca";
    src = fetchgit {
      url = "https://github.com/rust-lang/rust.vim";
      rev = "1cdc5cb4bd061bc30b502e07321682b5a4396dca";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-70kp644jOtJ4wguty/SUFX+YEsoxW12LGg3vZh7BdPY=";
    };
    date = "2022-09-28";
  };
  telescope-file-browser-nvim = {
    pname = "telescope-file-browser-nvim";
    version = "2429ecfd2d76e3eb6c9f8d8ba2c6ce328975a95a";
    src = fetchFromGitHub ({
      owner = "nvim-telescope";
      repo = "telescope-file-browser.nvim";
      rev = "2429ecfd2d76e3eb6c9f8d8ba2c6ce328975a95a";
      fetchSubmodules = false;
      sha256 = "sha256-fIm2FWYJXNl0SlQgmRuULOTRc2VVv2p1jJ2slcP4veY=";
    });
    date = "2022-10-16";
  };
}
