name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cancel-previous:
    runs-on: ubuntu-latest

    steps:
      # Cancel previous runs of this workflow that have not yet completed
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  check-flake:
    runs-on: ubuntu-latest

    steps:
      # Clone the repository
      - name: Clone
        uses: actions/checkout@v3

      # Install Nix onto the runner
      - name: Nix
        uses: cachix/install-nix-action@v20
        with:
          install_url: "https://releases.nixos.org/nix/nix-2.14.1/install"
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.PRIVATE_REPO_PAT }}

      # Set up my Cachix cache
      - name: Cachix
        uses: cachix/cachix-action@v12
        with:
          name: nerosnm
          authToken: ${{ secrets.CACHIX_KEY }}

      # Calculate the rev that the neros-dev input is locked to, so that we can
      # override the path to the input for ourselves and download the right
      # version. This is only a temporarily necessary measure because the repo
      # is private for the time being.
      - name: Input rev (neros-dev)
        run: |
          neros_dev_rev=$(nix flake metadata --json | nix shell nixpkgs#jq -c jq -r '.locks.nodes."neros-dev".locked.rev')
          echo "neros_dev_rev=${neros_dev_rev}" >> "$GITHUB_ENV"

      - name: Check Flake
        run: |
          nix flake check \
            -L \
            --accept-flake-config \
            --override-input neros-dev github:nerosnm/neros.dev/${neros_dev_rev}

  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        host:
          - atria

    steps:
      # Clone the repository.
      - name: Clone
        uses: actions/checkout@v3

      # Install Nix onto the runner.
      - name: Nix
        uses: cachix/install-nix-action@v20
        with:
          install_url: "https://releases.nixos.org/nix/nix-2.14.1/install"
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.PRIVATE_REPO_PAT }}

      # Set up my Cachix cache.
      - name: Cachix
        uses: cachix/cachix-action@v12
        with:
          name: nerosnm
          authToken: ${{ secrets.CACHIX_KEY }}

      # If there were previous runs of this workflow that set a cached value for
      # the last deployed path for this host, this step will restore the file
      # containing that value. This will also set up a post-workflow step that
      # will cache the value for *this* workflow, under the right conditions.
      - name: Cache last deployed path
        id: cache-last-deployed-path
        if: github.event_name == 'push'
        uses: actions/cache@v3
        with:
          key: v0-last-deployed-path-${{ matrix.host }}
          path: ./last-deployed-path

      # If the cache-last-deployed-path step found a cached value for the last
      # path that was deployed to this host, then this step will set an output
      # that determines whether the deploy should be skipped in this workflow
      # run (if the cached value is the same as the path that would be deployed
      # in this job, we don't need to run the deploy).
      - name: Skip duplicate deploy
        id: skip-duplicate-deploy
        if: steps.cache-last-deployed-path.outputs.cache-hit == 'true'
        run: |
          nix eval --raw .#deploy.nodes.${{ matrix.host }}.profiles.system.path.drvPath > ./would-deploy-path
          cmp ./would-deploy-path ./last-deployed-path \
            && echo "skip=true" >> "$GITHUB_OUTPUT" \
            || echo "skip=false" >> "$GITHUB_OUTPUT"

      # Set up Tailscale and log into the tailnet with an ephemeral authkey.
      - name: Tailscale
        if: steps.skip-duplicate-deploy.outputs.skip != 'true'
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      # Set up a private key and known-hosts info for each host.
      - name: SSH keys
        if: steps.skip-duplicate-deploy.outputs.skip != 'true'
        run: |
          mkdir -p ~/.ssh/
          echo "$ATRIA_DEPLOY_KEY" >> ~/.ssh/atria_deploy_key
          sudo chmod 600 ~/.ssh/atria_deploy_key
          echo "$ATRIA_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        shell: bash
        env:
          ATRIA_DEPLOY_KEY: ${{ secrets.ATRIA_DEPLOY_KEY }}
          ATRIA_KNOWN_HOSTS: ${{ secrets.ATRIA_KNOWN_HOSTS }}

      # Calculate the rev that the neros-dev input is locked to, so that we can
      # override the path to the input for ourselves and download the right
      # version. This is only a temporarily necessary measure because the repo
      # is private for the time being.
      - name: Input rev (neros-dev)
        if: steps.skip-duplicate-deploy.outputs.skip != 'true'
        run: |
          neros_dev_rev=$(nix flake metadata --json | nix shell nixpkgs#jq -c jq -r '.locks.nodes."neros-dev".locked.rev')
          echo "neros_dev_rev=${neros_dev_rev}" >> "$GITHUB_ENV"

      # Build the configuration for the host first.
      - name: Build (${{ matrix.host }})
        if: steps.skip-duplicate-deploy.outputs.skip != 'true'
        run: |
          nix build \
            -L \
            --accept-flake-config \
            --override-input neros-dev github:nerosnm/neros.dev/${neros_dev_rev} \
            .#deploy.nodes.${{ matrix.host }}.profiles.system.path.out

      # If we're not running in response to a push, then we're running on a pull
      # request, and we shouldn't *actually* deploy yet.
      - name: Set dry activation flag
        if: github.event_name != 'push'
        run: echo "dry_activation_flag=--dry-activate" >> "$GITHUB_ENV"

      # Deploy the configuration to the host (or dry-activate it if the flag was
      # set).
      - name: Deploy (${{ matrix.host }})
        if: steps.skip-duplicate-deploy.outputs.skip != 'true'
        run: |
          nix develop \
            -L \
            --accept-flake-config \
            --override-input neros-dev github:nerosnm/neros.dev/${neros_dev_rev} \
            -c \
            deploy \
            --ssh-opts="-i ~/.ssh/${{ matrix.host }}_deploy_key" \
            .#${{ matrix.host }} \
            ${dry_activation_flag} \
            -- \
            --accept-flake-config \
            --override-input neros-dev github:nerosnm/neros.dev/${neros_dev_rev}

      # Calculate the derivation path that was used for the deploy, and save it
      # to the `last-deployed-path` file. The post workflow step set up by the
      # cache-last-deployed-path step will save that file for future workflows
      # to read.
      - name: Calculate last deployed path
        if: github.event_name == 'push' && steps.skip-duplicate-deploy.outputs.skip != 'true'
        run: |
          nix eval --raw .#deploy.nodes.${{ matrix.host }}.profiles.system.path.drvPath > ./last-deployed-path
